apiVersion: apps/v1
kind: Deployment
metadata:
  name: lg-uplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uplus
  template:
    metadata:
      labels:
        app: uplus
    spec:
      containers:
        - name: lg-uplus
          image: AWS_ECR_URI
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
          resources:
            limits:
              cpu: 70m
            requests:
              cpu: 35m
