apiVersion: apps/v1
kind: Deployment
metadata:
  name: lg-uplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      containers:
        - name: eks
          image: AWS_ECR_URI
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 50m
